server:
  port: ${SERVER_PORT:8091} 
  
spring:
  application:
    name: admin-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}

grpc:
  server:
    port: ${GRPC_PORT:9091}
    reflection-service-enabled: true
  client:
    ser-service:
      address: static://localhost:9093 # container-name in docker
      negotiation-type: plaintext


logging:
  level:
    root: INFO
    org.springframework: INFO
