// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file admin/admin.proto (package admin, syntax proto3)
 

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/admin.proto.
 */
export const file_admin_admin: GenFile = /*@__PURE__*/
  fileDesc("ChFhZG1pbi9hZG1pbi5wcm90bxIFYWRtaW4iMwoRVXNlckFjdGlvblJlcXVlc3QSDgoGdXNlcklkGAEgASgEEg4KBnJlYXNvbhgDIAEoCSI2ChJVc2VyQWN0aW9uUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJIjkKFE1lc3NhZ2VBY3Rpb25SZXF1ZXN0EhEKCW1lc3NhZ2VJZBgBIAEoBBIOCgZyZWFzb24YAyABKAkiOQoVTWVzc2FnZUFjdGlvblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIwChZEbHRDb252ZXJzYXRpb25SZXF1ZXN0EhYKDmNvbnZlcnNhdGlvbklkGAEgASgEIjsKF0RsdENvbnZlcnNhdGlvblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCTLzAQoMQWRtaW5TZXJ2aWNlEkIKC1N1c3BlbmRVc2VyEhguYWRtaW4uVXNlckFjdGlvblJlcXVlc3QaGS5hZG1pbi5Vc2VyQWN0aW9uUmVzcG9uc2USSgoNRGVsZXRlTWVzc2FnZRIbLmFkbWluLk1lc3NhZ2VBY3Rpb25SZXF1ZXN0GhwuYWRtaW4uTWVzc2FnZUFjdGlvblJlc3BvbnNlElMKEkRlbGV0ZUNvbnZlcnNhdGlvbhIdLmFkbWluLkRsdENvbnZlcnNhdGlvblJlcXVlc3QaHi5hZG1pbi5EbHRDb252ZXJzYXRpb25SZXNwb25zZUIeCg5jb20uYWRpYS5hZG1pbkIKQWRtaW5Qcm90b1ABYgZwcm90bzM");

/**
 * @generated from message admin.UserActionRequest
 */
export type UserActionRequest = Message<"admin.UserActionRequest"> & {
  /**
   * @generated from field: uint64 userId = 1;
   */
  userId: bigint;

  /**
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message admin.UserActionRequest.
 * Use `create(UserActionRequestSchema)` to create a new message.
 */
export const UserActionRequestSchema: GenMessage<UserActionRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 0);

/**
 * @generated from message admin.UserActionResponse
 */
export type UserActionResponse = Message<"admin.UserActionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message admin.UserActionResponse.
 * Use `create(UserActionResponseSchema)` to create a new message.
 */
export const UserActionResponseSchema: GenMessage<UserActionResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 1);

/**
 * Messages pour la gestion des messages
 *
 * @generated from message admin.MessageActionRequest
 */
export type MessageActionRequest = Message<"admin.MessageActionRequest"> & {
  /**
   * @generated from field: uint64 messageId = 1;
   */
  messageId: bigint;

  /**
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message admin.MessageActionRequest.
 * Use `create(MessageActionRequestSchema)` to create a new message.
 */
export const MessageActionRequestSchema: GenMessage<MessageActionRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 2);

/**
 * @generated from message admin.MessageActionResponse
 */
export type MessageActionResponse = Message<"admin.MessageActionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message admin.MessageActionResponse.
 * Use `create(MessageActionResponseSchema)` to create a new message.
 */
export const MessageActionResponseSchema: GenMessage<MessageActionResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 3);

/**
 * @generated from message admin.DltConversationRequest
 */
export type DltConversationRequest = Message<"admin.DltConversationRequest"> & {
  /**
   * @generated from field: uint64 conversationId = 1;
   */
  conversationId: bigint;
};

/**
 * Describes the message admin.DltConversationRequest.
 * Use `create(DltConversationRequestSchema)` to create a new message.
 */
export const DltConversationRequestSchema: GenMessage<DltConversationRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 4);

/**
 * @generated from message admin.DltConversationResponse
 */
export type DltConversationResponse = Message<"admin.DltConversationResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message admin.DltConversationResponse.
 * Use `create(DltConversationResponseSchema)` to create a new message.
 */
export const DltConversationResponseSchema: GenMessage<DltConversationResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 5);

/**
 * Service d'administration
 *
 * @generated from service admin.AdminService
 */
export const AdminService: GenService<{
  /**
   * @generated from rpc admin.AdminService.SuspendUser
   */
  suspendUser: {
    methodKind: "unary";
    input: typeof UserActionRequestSchema;
    output: typeof UserActionResponseSchema;
  },
  /**
   * @generated from rpc admin.AdminService.DeleteMessage
   */
  deleteMessage: {
    methodKind: "unary";
    input: typeof MessageActionRequestSchema;
    output: typeof MessageActionResponseSchema;
  },
  /**
   * rpc DoCheck (CheckRequest) returns (CheckResponse);
   *
   * @generated from rpc admin.AdminService.DeleteConversation
   */
  deleteConversation: {
    methodKind: "unary";
    input: typeof DltConversationRequestSchema;
    output: typeof DltConversationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_admin, 0);

