apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-messenger-config
  namespace: grpc-messenger
data:
  # Service Ports
  ADMIN_PORT: "9091"
  AUTH_PORT: "9092"
  USER_PORT: "9093"
  CHAT_PORT: "9094"
  NOTIFICATION_PORT: "9095"
  
  SERVER_ADMIN_PORT: "8091"
  SERVER_AUTH_PORT: "8092"
  SERVER_USER_PORT: "8093"
  SERVER_CHAT_PORT: "8094"
  SERVER_NOTIFICATION_PORT: "8095"
  
  # Spring Boot
  SPRING_PROFILES_ACTIVE: "prod"
  
  # Database
  DB_HOST: "mysql-service"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/chatdb"
  SPRING_DATASOURCE_USERNAME: "chatuser"
  
  # Redis
  REDIS_HOST: "redis-service"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  
  # Envoy
  ENVOY_PORT: "8080"