// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file auth/auth.proto (package auth, syntax proto3)
 

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { User } from "../user/user_pb";
import { file_user_user } from "../user/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/auth.proto.
 */
export const file_auth_auth: GenFile = /*@__PURE__*/
  fileDesc("Cg9hdXRoL2F1dGgucHJvdG8SBGF1dGgiRAoPUmVnaXN0ZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJIi8KDExvZ2luUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIfCg1Mb2dvdXRSZXF1ZXN0Eg4KBnVzZXJJZBgBIAEoBCIHCgVFbXB0eSIrChNSZWZyZXNoVG9rZW5SZXF1ZXN0EhQKDHJlZnJlc2hUb2tlbhgBIAEoCSIdCgxUb2tlblJlcXVlc3QSDQoFdG9rZW4YASABKAkiiAEKDEF1dGhSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSEwoLYWNjZXNzVG9rZW4YAyABKAkSFAoMcmVmcmVzaFRva2VuGAQgASgJEhEKCWV4cGlyZXNJbhgFIAEoAxIYCgR1c2VyGAYgASgLMgoudXNlci5Vc2VyImAKE1ZlcmlmeVRva2VuUmVzcG9uc2USDQoFdmFsaWQYASABKAgSDwoHbWVzc2FnZRgCIAEoCRIYCgR1c2VyGAMgASgLMgoudXNlci5Vc2VyEg8KB3N1Y2Nlc3MYBCABKAgyngIKC0F1dGhTZXJ2aWNlEjUKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaEi5hdXRoLkF1dGhSZXNwb25zZRIvCgVMb2dpbhISLmF1dGguTG9naW5SZXF1ZXN0GhIuYXV0aC5BdXRoUmVzcG9uc2USKgoGTG9nb3V0EhMuYXV0aC5Mb2dvdXRSZXF1ZXN0GgsuYXV0aC5FbXB0eRI8CgtWZXJpZnlUb2tlbhISLmF1dGguVG9rZW5SZXF1ZXN0GhkuYXV0aC5WZXJpZnlUb2tlblJlc3BvbnNlEj0KDFJlZnJlc2hUb2tlbhIZLmF1dGguUmVmcmVzaFRva2VuUmVxdWVzdBoSLmF1dGguQXV0aFJlc3BvbnNlQhwKDWNvbS5hZGlhLmF1dGhCCUF1dGhQcm90b1ABYgZwcm90bzM", [file_user_user]);

/**
 * @generated from message auth.RegisterRequest
 */
export type RegisterRequest = Message<"auth.RegisterRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth, 0);

/**
 * @generated from message auth.LoginRequest
 */
export type LoginRequest = Message<"auth.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth, 1);

/**
 * @generated from message auth.LogoutRequest
 */
export type LogoutRequest = Message<"auth.LogoutRequest"> & {
  /**
   * @generated from field: uint64 userId = 1;
   */
  userId: bigint;
};

/**
 * Describes the message auth.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth, 2);

/**
 * @generated from message auth.Empty
 */
export type Empty = Message<"auth.Empty"> & {
};

/**
 * Describes the message auth.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_auth_auth, 3);

/**
 * @generated from message auth.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"auth.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refreshToken = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth, 4);

/**
 * @generated from message auth.TokenRequest
 */
export type TokenRequest = Message<"auth.TokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message auth.TokenRequest.
 * Use `create(TokenRequestSchema)` to create a new message.
 */
export const TokenRequestSchema: GenMessage<TokenRequest> = /*@__PURE__*/
  messageDesc(file_auth_auth, 5);

/**
 * @generated from message auth.AuthResponse
 */
export type AuthResponse = Message<"auth.AuthResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string accessToken = 3;
   */
  accessToken: string;

  /**
   * @generated from field: string refreshToken = 4;
   */
  refreshToken: string;

  /**
   * @generated from field: int64 expiresIn = 5;
   */
  expiresIn: bigint;

  /**
   * @generated from field: user.User user = 6;
   */
  user?: User;
};

/**
 * Describes the message auth.AuthResponse.
 * Use `create(AuthResponseSchema)` to create a new message.
 */
export const AuthResponseSchema: GenMessage<AuthResponse> = /*@__PURE__*/
  messageDesc(file_auth_auth, 6);

/**
 * @generated from message auth.VerifyTokenResponse
 */
export type VerifyTokenResponse = Message<"auth.VerifyTokenResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: user.User user = 3;
   */
  user?: User;

  /**
   * @generated from field: bool success = 4;
   */
  success: boolean;
};

/**
 * Describes the message auth.VerifyTokenResponse.
 * Use `create(VerifyTokenResponseSchema)` to create a new message.
 */
export const VerifyTokenResponseSchema: GenMessage<VerifyTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth_auth, 7);

/**
 * @generated from service auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof AuthResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc auth.AuthService.VerifyToken
   */
  verifyToken: {
    methodKind: "unary";
    input: typeof TokenRequestSchema;
    output: typeof VerifyTokenResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof AuthResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_auth, 0);

