// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file notification/notification.proto (package notification, syntax proto3)
 

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file notification/notification.proto.
 */
export const file_notification_notification: GenFile = /*@__PURE__*/
  fileDesc("Ch9ub3RpZmljYXRpb24vbm90aWZpY2F0aW9uLnByb3RvEgxub3RpZmljYXRpb24iHQoLVXNlclJlcXVlc3QSDgoGdXNlcklkGAEgASgJIq0BCgxOb3RpZmljYXRpb24SCgoCaWQYASABKAkSEgoKcmVjZWl2ZXJJZBgCIAEoCRIQCghzZW5kZXJJZBgDIAEoCRIPCgdjb250ZW50GAQgASgJEg0KBXRpdGxlGAYgASgJEgwKBGxpbmsYByABKAkSLQoJY3JlYXRlZEF0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIOCgZ1bnJlYWQYCSABKAgiVAoMU2VuZE5vdGlmUmVxEhIKCnJlY2VpdmVySWQYAiABKAkSEAoIc2VuZGVySWQYAyABKAkSDwoHY29udGVudBgEIAEoCRINCgV0aXRsZRgGIAEoCSJaChBOb3RpZmljYXRpb25MaXN0EjEKDW5vdGlmaWNhdGlvbnMYASADKAsyGi5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uEhMKC3VucmVhZENvdW50GAIgASgFIjkKFk5ld05vdGlmaWNhdGlvblJlcXVlc3QSDgoGdXNlcklkGAEgASgJEg8KB21lc3NhZ2UYAiABKAkiSwoSR3JvdXBJbnZpdGVSZXF1ZXN0EhEKCWludml0ZXJJZBgBIAEoCRIRCglpbnZpdGVlSWQYAiABKAkSDwoHZ3JvdXBJZBgDIAEoCSI8CgdSZWFkUmVxEjEKDW5vdGlmaWNhdGlvbnMYASADKAsyGi5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uMucDChNOb3RpZmljYXRpb25TZXJ2aWNlEk4KE1N0cmVhbU5vdGlmaWNhdGlvbnMSGS5ub3RpZmljYXRpb24uVXNlclJlcXVlc3QaGi5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uMAESVgoSQ3JlYXRlTm90aWZpY2F0aW9uEiQubm90aWZpY2F0aW9uLk5ld05vdGlmaWNhdGlvblJlcXVlc3QaGi5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uElEKEU5vdGlmeUdyb3VwSW52aXRlEiAubm90aWZpY2F0aW9uLkdyb3VwSW52aXRlUmVxdWVzdBoaLm5vdGlmaWNhdGlvbi5Ob3RpZmljYXRpb24SUAoTZ2V0QWxsTm90aWZpY2F0aW9ucxIZLm5vdGlmaWNhdGlvbi5Vc2VyUmVxdWVzdBoeLm5vdGlmaWNhdGlvbi5Ob3RpZmljYXRpb25MaXN0EkYKEFNlbmROb3RpZmljYXRpb24SGi5ub3RpZmljYXRpb24uU2VuZE5vdGlmUmVxGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EjsKCk1hcmtBc1JlYWQSFS5ub3RpZmljYXRpb24uUmVhZFJlcRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eUIsChVjb20uYWRpYS5ub3RpZmljYXRpb25CEU5vdGlmaWNhdGlvblByb3RvUAFiBnByb3RvMw", [file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * @generated from message notification.UserRequest
 */
export type UserRequest = Message<"notification.UserRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;
};

/**
 * Describes the message notification.UserRequest.
 * Use `create(UserRequestSchema)` to create a new message.
 */
export const UserRequestSchema: GenMessage<UserRequest> = /*@__PURE__*/
  messageDesc(file_notification_notification, 0);

/**
 * @generated from message notification.Notification
 */
export type Notification = Message<"notification.Notification"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string receiverId = 2;
   */
  receiverId: string;

  /**
   * @generated from field: string senderId = 3;
   */
  senderId: string;

  /**
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * @generated from field: string title = 6;
   */
  title: string;

  /**
   * Optional URL or frontend route (e.g. "/group/123")
   *
   * @generated from field: string link = 7;
   */
  link: string;

  /**
   * @generated from field: google.protobuf.Timestamp createdAt = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: bool unread = 9;
   */
  unread: boolean;
};

/**
 * Describes the message notification.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema: GenMessage<Notification> = /*@__PURE__*/
  messageDesc(file_notification_notification, 1);

/**
 * @generated from message notification.SendNotifReq
 */
export type SendNotifReq = Message<"notification.SendNotifReq"> & {
  /**
   * @generated from field: string receiverId = 2;
   */
  receiverId: string;

  /**
   * @generated from field: string senderId = 3;
   */
  senderId: string;

  /**
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * @generated from field: string title = 6;
   */
  title: string;
};

/**
 * Describes the message notification.SendNotifReq.
 * Use `create(SendNotifReqSchema)` to create a new message.
 */
export const SendNotifReqSchema: GenMessage<SendNotifReq> = /*@__PURE__*/
  messageDesc(file_notification_notification, 2);

/**
 * @generated from message notification.NotificationList
 */
export type NotificationList = Message<"notification.NotificationList"> & {
  /**
   * @generated from field: repeated notification.Notification notifications = 1;
   */
  notifications: Notification[];

  /**
   * @generated from field: int32 unreadCount = 2;
   */
  unreadCount: number;
};

/**
 * Describes the message notification.NotificationList.
 * Use `create(NotificationListSchema)` to create a new message.
 */
export const NotificationListSchema: GenMessage<NotificationList> = /*@__PURE__*/
  messageDesc(file_notification_notification, 3);

/**
 * @generated from message notification.NewNotificationRequest
 */
export type NewNotificationRequest = Message<"notification.NewNotificationRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message notification.NewNotificationRequest.
 * Use `create(NewNotificationRequestSchema)` to create a new message.
 */
export const NewNotificationRequestSchema: GenMessage<NewNotificationRequest> = /*@__PURE__*/
  messageDesc(file_notification_notification, 4);

/**
 * @generated from message notification.GroupInviteRequest
 */
export type GroupInviteRequest = Message<"notification.GroupInviteRequest"> & {
  /**
   * @generated from field: string inviterId = 1;
   */
  inviterId: string;

  /**
   * @generated from field: string inviteeId = 2;
   */
  inviteeId: string;

  /**
   * @generated from field: string groupId = 3;
   */
  groupId: string;
};

/**
 * Describes the message notification.GroupInviteRequest.
 * Use `create(GroupInviteRequestSchema)` to create a new message.
 */
export const GroupInviteRequestSchema: GenMessage<GroupInviteRequest> = /*@__PURE__*/
  messageDesc(file_notification_notification, 5);

/**
 * @generated from message notification.ReadReq
 */
export type ReadReq = Message<"notification.ReadReq"> & {
  /**
   * @generated from field: repeated notification.Notification notifications = 1;
   */
  notifications: Notification[];
};

/**
 * Describes the message notification.ReadReq.
 * Use `create(ReadReqSchema)` to create a new message.
 */
export const ReadReqSchema: GenMessage<ReadReq> = /*@__PURE__*/
  messageDesc(file_notification_notification, 6);

/**
 * Service de notifications
 *
 * @generated from service notification.NotificationService
 */
export const NotificationService: GenService<{
  /**
   * @generated from rpc notification.NotificationService.StreamNotifications
   */
  streamNotifications: {
    methodKind: "server_streaming";
    input: typeof UserRequestSchema;
    output: typeof NotificationSchema;
  },
  /**
   * @generated from rpc notification.NotificationService.CreateNotification
   */
  createNotification: {
    methodKind: "unary";
    input: typeof NewNotificationRequestSchema;
    output: typeof NotificationSchema;
  },
  /**
   * @generated from rpc notification.NotificationService.NotifyGroupInvite
   */
  notifyGroupInvite: {
    methodKind: "unary";
    input: typeof GroupInviteRequestSchema;
    output: typeof NotificationSchema;
  },
  /**
   * when user login get Notifi history whith count of unread
   *
   * @generated from rpc notification.NotificationService.getAllNotifications
   */
  getAllNotifications: {
    methodKind: "unary";
    input: typeof UserRequestSchema;
    output: typeof NotificationListSchema;
  },
  /**
   * @generated from rpc notification.NotificationService.SendNotification
   */
  sendNotification: {
    methodKind: "unary";
    input: typeof SendNotifReqSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc notification.NotificationService.MarkAsRead
   */
  markAsRead: {
    methodKind: "unary";
    input: typeof ReadReqSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_notification_notification, 0);

